spring:
  kafka:
    producer:
      bootstrap-servers: http://localhost:9092
    consumer:
      bootstrap-servers: http://localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
  data:
    mongodb:
      uri: mongodb://localhost/kafka
      username: root
      password: root

kafka:
  queues:
    product:
      name: KAFKA-PRODUCT
      read:
        listener-bean-id: processingMessageReadingFromProductQueues